// process.env.NODE_TLS_REJECT_UNAUTHORIZED = '0';

import yaml from 'js-yaml'
import fs from 'fs'
import { paths } from './FormatRequest'
import { init } from './init'

process.on('beforeExit', code => {
    SaveSpecs()
    process.exit(code)
})

process.on('uncaughtException', err => {
    console.log(`Uncaught Exception: ${err.message}`)
    SaveSpecs()
    process.exit(1)
})

process.on('unhandledRejection', (reason, promise) => {
    console.log('Unhandled rejection at ', promise, `reason: ${err.message}`)
    SaveSpecs()
    process.exit(1)
})

process.on('SIGINT', async () => {
    SaveSpecs()
    process.exit(0)
})

process.on('SIGTERM', async () => {
    SaveSpecs()
    process.exit(1)
})

init()
function SaveSpecs() {
    console.log(`saving api specs ... `)
    const specs = {
        openapi: '3.0.0',
        info: {
            title: 'API',
            description: 'auto-generated by swagger proxy',
            version: '1.0'
        },
        servers: [
            { url: '' }
        ],
        paths: Object.fromEntries(paths),
    }
    console.log(`Saving to specs.yaml ...`)
    fs.writeFileSync('specs.json', JSON.stringify(specs))
    fs.writeFileSync('specs.yaml', yaml.safeDump(specs, {
        indent: 2,
    }))
    console.log('done')
}

